name: "bluebell"
mode: "dev"
port: 8084
version: "v0.0.1"
start_time: "2025-05-26"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: 0.0.0.0
  port: "3308"
  user: "root"
  password: "root1234"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  hose: 0.0.0.0
  port: "26379"
  password: ""
  db: 0
  pool_size: 100